### ISSUE TITLE
should "disrespect" category be "xenophobia"?

### ISSUE THREAD

**Issue by russellgoldenberg** [the-pudding/censorship#31]

**Comment by robsmithwashere** [comment]
I'm not sure all of the examples here (namely the 3rd vid, and to some
degree the 2nd as well) would fall into a bog standard definition of
xenopohbia (when bog standard equals American Heritage): fear, hatred,
mistrust or contempt.  Something to put to a 2nd reader.

*Rob Smith *(he/him)
Managing Director
*The Pudding* <https://pudding.cool/>

**Comment by robsmithwashere** [comment]
never mind, I was watching the set of clips that come after the text, not before.

**Comment by robsmithwashere** [comment]
oh I see. Looking through the rest of the entries on the spreadsheet, there are some that a little less clearly defined.  I'm going to go back to my earlier plan and make this a question for a sensitivity reader.
