### ISSUE TITLE
would take out example 4 in the xenophobia section

### ISSUE THREAD

**Issue by robsmithwashere** [the-pudding/censorship#53]
Readers will have seen it twice already by then

<img width="611" alt="Screen Shot 2022-06-30 at 6 21 53 PM" src="https://user-images.githubusercontent.com/88445968/176788508-b2d97ab9-4775-4683-8185-e3b75a637d6e.png">

**Comment by russellgoldenberg** [comment]
removed it in google doc but hadn't updated site yet
