### ISSUE TITLE
i might add a dek that explains the point of the story (big censored theory is pretty vague)

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/censorship#65]
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/2880174/186990749-b22ee1b3-3316-409c-b5f0-cd4b056767dd.png">

**Comment by manyunzou** [comment]
I agree. How about - "a visual explainer to demonstrate how the popular American sitcom got censored in China and decipher the logic behind the decision"?
