### ISSUE TITLE
Because of Love

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/censorship#69]
I might preface here that Because of Love is a drama series endemic to China (Basically I had to google the series to figure out whether it was American)

<img width="704" alt="image" src="https://user-images.githubusercontent.com/2880174/186991760-d7860c25-ee36-4373-8dd6-11e97277d01d.png">

**Comment by manyunzou** [comment]
I agree. Can we add a "Chinese drama" in front of the Because of Love?
